name: Inject API key and deploy

on:
  push:
    branches:
      - main

jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Replace API key in HTML
        run: |
          find . -type f -name "*.html" -exec sed -i \
            "s/__OPENAI_API_KEY__/${{ secrets.OPENAI_API_KEY }}/g" {} +

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Inject API key" || echo "No changes to commit"
          git push
